[project]
name = "receiver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7.13"
dependencies = [
    "hidapi>=0.14.0.post4",
    "joycon-python>=0.2.4",
    "matplotlib>=3.5.3",
    "numpy>=1.21.6",
    "pyglm>=2.8.0",
]
